/* =========================================================
   Code Origin.AI — AWS Cloud Lab (Workshop Day 1)
   A full course-player dataset: every Day-1 AWS topic with an
   easy explanation, a real-life analogy, key points, a runnable
   "live example", and an assigned animated graphic.
   Attaches to window.DATA.aws (data.js runs first).
   ========================================================= */
(function () {
  if (!window.DATA) window.DATA = {};

  // Ordered sessions -> topic ids (controls prev/next + the rail)
  const sessions = [
    { label: "Session 1", time: "08:40 AM – 10:40 AM", ico: "🌅", ids: [
      "cloud", "global", "account", "iam", "cli", "vpc", "subnets", "igw", "routes", "sg", "nacl",
    ] },
    { label: "Session 2", time: "11:00 AM – 01:00 PM", ico: "🌤️", ids: [
      "ec2", "osservers", "lifecycle", "customvpc", "s3", "storageclasses", "staticsite",
    ] },
    { label: "Session 3", time: "01:45 PM – 03:45 PM", ico: "🌇", ids: [
      "rds", "dbconn", "backup", "peering", "transit", "alb", "targets", "asg", "lambda", "dynamo",
    ] },
  ];

  const L = {
    cloud: {
      ico: "☁️", title: "Introduction to Cloud Computing", graphic: "cloud",
      oneLine: "Renting computing power, storage and software over the internet instead of buying and running your own machines.",
      analogy: "🔌 Like using electricity from the grid: you flip a switch and pay for what you use — you don't build your own power plant.",
      explain: "Traditionally, companies bought physical servers, kept them in a room, powered and cooled them, and replaced them when they broke. The cloud flips this: a provider like AWS owns massive data centers, and you rent exactly what you need, when you need it, paying by the hour or even by the second. You can get 1 server or 1,000 in minutes, then give them back when you're done.",
      points: [
        "No upfront hardware cost — pay-as-you-go",
        "Scale up or down in minutes, globally",
        "The provider handles power, cooling, security & hardware",
        "Three models: IaaS (servers), PaaS (platforms), SaaS (apps)",
      ],
      example: { label: "On-prem vs Cloud — the difference", lines: [
        "# Old way (on-premises): buy a server, wait weeks, set it up",
        "$ order-server --cpu 8 --ram 32GB   # arrives in 3-6 weeks 😴",
        "",
        "# Cloud way (AWS): launch in seconds, pay per hour",
        "$ aws ec2 run-instances --instance-type t3.large --count 1",
        "  -> InstanceId: i-0ab12cd34  State: pending -> running ✅",
        "  Ready in ~60 seconds. Stop it anytime to stop paying.",
      ] },
    },
    global: {
      ico: "🌍", title: "AWS Global Infrastructure", graphic: "globe",
      oneLine: "The worldwide network of AWS data centers, organised into Regions, Availability Zones and Edge Locations.",
      analogy: "🏬 Like a global chain of warehouses: many cities (Regions), each with several separate buildings (Availability Zones) so one fire never stops everything.",
      explain: "A Region is a geographic area (e.g. Mumbai, N. Virginia). Each Region contains multiple Availability Zones (AZs) — physically separate data centers with their own power and network, close enough for fast links but far enough to fail independently. Edge Locations are hundreds of smaller sites worldwide that cache content near users for speed (used by CloudFront).",
      points: [
        "Region = a city/area (pick one near your users for low latency)",
        "Availability Zone = an isolated data center inside a Region",
        "Run across 2+ AZs for high availability",
        "Edge Locations cache content close to users worldwide",
      ],
      example: { label: "Listing AWS Regions", lines: [
        "$ aws ec2 describe-regions --query 'Regions[].RegionName' --output table",
        "----------------------------",
        "| ap-south-1     (Mumbai)   |",
        "| us-east-1      (Virginia) |",
        "| eu-west-1      (Ireland)  |",
        "| ap-southeast-1 (Singapore)|",
        "----------------------------",
        "# Tip: deploy in the Region closest to your customers.",
      ] },
    },
    account: {
      ico: "🔐", title: "AWS Account Setup", graphic: "iam",
      oneLine: "Creating your AWS account and securing the all-powerful master (root) login.",
      analogy: "🏦 Like opening a bank account and locking the master key in a safe — you use it only for emergencies.",
      explain: "When you sign up, you get a 'root user' that can do anything, including closing the account. Best practice: protect root with Multi-Factor Authentication (MFA), set up billing alerts so you never get surprise bills, and then create everyday IAM users/roles for actual work instead of using root.",
      points: [
        "Root user = unlimited power; protect it with MFA",
        "Never use root for daily tasks — create IAM users",
        "Set a billing alarm to avoid surprise costs",
        "Enable CloudTrail to log everything that happens",
      ],
      example: { label: "First things after sign-up", lines: [
        "1. Enable MFA on the root user (phone authenticator app)",
        "2. Create a billing alarm:",
        "$ aws cloudwatch put-metric-alarm --alarm-name billing-10usd \\",
        "    --metric-name EstimatedCharges --threshold 10 ...",
        "3. Create an admin IAM user for daily use (next topic).",
        "   ✅ Root key now stays locked away.",
      ] },
    },
    iam: {
      ico: "🪪", title: "IAM — Identity & Access Management", graphic: "iam",
      oneLine: "Controls WHO can do WHAT on WHICH resources in your AWS account.",
      analogy: "🪪 Like office keycards: each employee's card opens only the rooms they need — not the whole building.",
      explain: "IAM has four building blocks. Users are people or apps. Groups bundle users so you assign permissions once. Roles are temporary identities that services or users 'assume' (great for EC2/Lambda). Policies are JSON documents listing allowed/denied actions. The golden rule is least privilege: give the minimum access needed.",
      points: [
        "Users, Groups, Roles, Policies are the 4 pieces",
        "Policies are JSON: Effect (Allow/Deny), Action, Resource",
        "Roles give temporary, safer access (no stored passwords)",
        "Follow least privilege — start locked down, open as needed",
      ],
      example: { label: "A policy that allows read-only S3", lines: [
        "{",
        '  "Version": "2012-10-17",',
        '  "Statement": [{',
        '    "Effect": "Allow",',
        '    "Action": ["s3:GetObject", "s3:ListBucket"],',
        '    "Resource": "arn:aws:s3:::my-bucket/*"',
        "  }]",
        "}",
        "# This identity can READ my-bucket, but cannot delete or write.",
      ] },
    },
    cli: {
      ico: "⌨️", title: "AWS CLI", graphic: "cli",
      oneLine: "A command-line tool to control AWS by typing commands instead of clicking the web console.",
      analogy: "💬 Like texting precise instructions to AWS — fast, repeatable, and easy to automate in scripts.",
      explain: "The AWS Command Line Interface lets you run any AWS action from a terminal. You configure it once with your access keys and default region, then every service (EC2, S3, IAM…) is available as a command. It's the foundation of automation and scripting.",
      points: [
        "One tool for every AWS service",
        "Configure once: keys + default region + output format",
        "Perfect for scripts, automation and CI/CD",
        "Use --query and --output to shape results",
      ],
      example: { label: "Configure and use the CLI", lines: [
        "$ aws configure",
        "  AWS Access Key ID     : ********************",
        "  AWS Secret Access Key : ********************",
        "  Default region name   : ap-south-1",
        "  Default output format : json",
        "$ aws s3 ls",
        "  2026-06-29 10:14:02  my-bucket",
        "  ✅ Connected — you're now driving AWS from the terminal.",
      ] },
    },
    vpc: {
      ico: "🏗️", title: "VPC Architecture", graphic: "vpc",
      oneLine: "Your own private, isolated network inside AWS where your resources live.",
      analogy: "🏘️ Like getting your own fenced plot of land inside a huge city — you decide the roads, gates and rooms.",
      explain: "A Virtual Private Cloud is a logically isolated network you fully control. You pick an IP address range (CIDR, e.g. 10.0.0.0/16), then carve it into subnets, attach gateways for internet access, and add routing and firewalls. Everything you build (servers, databases) sits inside the VPC.",
      points: [
        "You choose the private IP range (CIDR block)",
        "Split it into subnets across Availability Zones",
        "Add gateways (IGW/NAT) to control internet access",
        "Completely isolated from other customers' networks",
      ],
      example: { label: "Create a VPC", lines: [
        "$ aws ec2 create-vpc --cidr-block 10.0.0.0/16",
        "  -> VpcId: vpc-0a1b2c  (65,536 private IPs available)",
        "# Inside this VPC you'll add subnets, an internet gateway,",
        "# route tables and security groups — the next few topics.",
      ] },
    },
    subnets: {
      ico: "🧩", title: "Public & Private Subnets", graphic: "vpc", focus: "subnets",
      oneLine: "Dividing your VPC into parts that face the internet (public) or stay hidden (private).",
      analogy: "🏢 Like a building's open lobby (public) versus the locked back offices (private) that visitors can't reach.",
      explain: "A subnet is a slice of your VPC's IP range, living in one Availability Zone. A public subnet has a route to the Internet Gateway, so things in it (like web servers) can be reached from the internet. A private subnet has no direct internet route — perfect for databases and back-end servers that should stay hidden.",
      points: [
        "Subnet = a slice of the VPC in one AZ",
        "Public subnet → has a route to the Internet Gateway",
        "Private subnet → no direct internet route (safer)",
        "Web servers go public; databases go private",
      ],
      example: { label: "Create public + private subnets", lines: [
        "$ aws ec2 create-subnet --vpc-id vpc-0a1b2c --cidr-block 10.0.1.0/24",
        "  -> subnet-pub  (public:  web servers live here)",
        "$ aws ec2 create-subnet --vpc-id vpc-0a1b2c --cidr-block 10.0.2.0/24",
        "  -> subnet-priv (private: database lives here)",
      ] },
    },
    igw: {
      ico: "🚪", title: "Internet Gateway (IGW)", graphic: "vpc", focus: "igw",
      oneLine: "The door that connects your VPC to the public internet.",
      analogy: "🚪 Like the main gate of a gated community — without it, no traffic gets in or out.",
      explain: "An Internet Gateway is attached to your VPC and lets resources in public subnets send and receive internet traffic. By itself it does nothing — you must also add a route in the subnet's route table that points internet-bound traffic (0.0.0.0/0) to the IGW.",
      points: [
        "Attaches to the VPC (one per VPC)",
        "Enables internet access for public subnets",
        "Needs a route 0.0.0.0/0 → IGW to actually work",
        "Private subnets use a NAT gateway instead (outbound only)",
      ],
      example: { label: "Attach an Internet Gateway", lines: [
        "$ aws ec2 create-internet-gateway        -> igw-09ff",
        "$ aws ec2 attach-internet-gateway \\",
        "    --internet-gateway-id igw-09ff --vpc-id vpc-0a1b2c",
        "# Next: add a route so the public subnet can use it.",
      ] },
    },
    routes: {
      ico: "🪧", title: "Route Tables", graphic: "vpc", focus: "routes",
      oneLine: "Rules that decide where network traffic should go.",
      analogy: "🪧 Like road signs at a junction directing each car to the correct destination.",
      explain: "Every subnet is associated with a route table — a list of rules saying 'traffic for THIS destination goes to THAT target.' A public subnet's table has a rule sending 0.0.0.0/0 (the whole internet) to the Internet Gateway. Local VPC traffic always stays inside automatically.",
      points: [
        "Maps destination IP ranges → targets (IGW, NAT, peering…)",
        "Public subnet route: 0.0.0.0/0 → Internet Gateway",
        "Local VPC route exists by default",
        "Each subnet uses exactly one route table",
      ],
      example: { label: "Make a subnet public via routing", lines: [
        "$ aws ec2 create-route --route-table-id rtb-pub \\",
        "    --destination-cidr-block 0.0.0.0/0 \\",
        "    --gateway-id igw-09ff",
        "# Now traffic to the internet leaves through the IGW.",
        "# Associate it with the public subnet:",
        "$ aws ec2 associate-route-table --route-table-id rtb-pub --subnet-id subnet-pub",
      ] },
    },
    sg: {
      ico: "💂", title: "Security Groups", graphic: "vpc", focus: "sg",
      oneLine: "A virtual firewall wrapped around each server, controlling allowed traffic.",
      analogy: "💂 Like a personal bouncer at each door, checking who is allowed in — and remembering to let their reply back out.",
      explain: "Security Groups operate at the instance level and are stateful: if you allow incoming traffic on a port, the response is automatically allowed back out. You only write ALLOW rules (there's an implicit deny). Example: allow port 22 (SSH) from your IP and port 80/443 (web) from anyone.",
      points: [
        "Instance-level, stateful firewall",
        "Only ALLOW rules; everything else is denied",
        "Return traffic is automatically permitted",
        "Reference other SGs (e.g. only web tier can reach DB)",
      ],
      example: { label: "Allow web + SSH traffic", lines: [
        "$ aws ec2 authorize-security-group-ingress --group-id sg-web \\",
        "    --protocol tcp --port 443 --cidr 0.0.0.0/0    # HTTPS from anyone",
        "$ aws ec2 authorize-security-group-ingress --group-id sg-web \\",
        "    --protocol tcp --port 22 --cidr 203.0.113.5/32 # SSH only from me",
      ] },
    },
    nacl: {
      ico: "🚧", title: "NACLs (Network ACLs)", graphic: "vpc", focus: "nacl",
      oneLine: "A firewall at the subnet level — an extra, broader layer of filtering.",
      analogy: "🚧 Like the neighbourhood security gate you pass before you even reach your own house's door (the Security Group).",
      explain: "Network ACLs guard the whole subnet and are stateless: you must write rules for BOTH incoming and outgoing traffic. Rules are numbered and evaluated in order. NACLs are a coarse, second line of defense; Security Groups remain your main, fine-grained control at each instance.",
      points: [
        "Subnet-level, stateless (rules for both directions)",
        "Numbered rules evaluated lowest-first",
        "Can explicitly DENY (Security Groups cannot)",
        "Defense-in-depth: NACL (broad) + SG (precise)",
      ],
      example: { label: "Block one bad IP at the subnet edge", lines: [
        "$ aws ec2 create-network-acl-entry --network-acl-id acl-01 \\",
        "    --rule-number 100 --protocol -1 --rule-action deny \\",
        "    --ingress --cidr-block 198.51.100.10/32",
        "# That IP is now blocked for the ENTIRE subnet.",
      ] },
    },
    ec2: {
      ico: "🖥️", title: "EC2 Deployment", graphic: "ec2",
      oneLine: "Launching virtual servers (instances) in the cloud to run your applications.",
      analogy: "🖥️ Like renting a computer in a data center by the hour — choose the size, switch it on, use it, switch it off.",
      explain: "Elastic Compute Cloud gives you resizable virtual machines. You pick an AMI (the OS image), an instance type (CPU/RAM size like t3.micro), a key pair (for secure login), a subnet and a security group. AWS launches it in about a minute and you connect via SSH or RDP.",
      points: [
        "AMI = the operating-system image to boot from",
        "Instance type = the size (vCPU + memory)",
        "Key pair = your secure login credentials",
        "Pay per second while running; stop to pause billing",
      ],
      example: { label: "Launch a web server", lines: [
        "$ aws ec2 run-instances \\",
        "    --image-id ami-0abc123 --instance-type t3.micro \\",
        "    --key-name my-key --security-group-ids sg-web \\",
        "    --subnet-id subnet-pub",
        "  -> i-0web01  State: pending -> running ✅",
        "$ ssh -i my-key.pem ec2-user@<public-ip>   # you're in!",
      ] },
    },
    osservers: {
      ico: "📀", title: "Linux & Windows Servers", graphic: "ec2", focus: "os",
      oneLine: "Choosing the operating system your EC2 server runs.",
      analogy: "📱 Like choosing Android vs iPhone — different systems, you pick the one your app needs.",
      explain: "EC2 supports many OS images: Amazon Linux, Ubuntu, Red Hat, and Windows Server. Linux is connected to over SSH (port 22) and is common for web/back-end apps. Windows is connected to over RDP (port 3389) and is used for .NET apps or Windows-only software. The OS is baked into the AMI you choose at launch.",
      points: [
        "Linux: connect via SSH (port 22)",
        "Windows: connect via RDP (port 3389)",
        "Pick the AMI that matches your app's needs",
        "Same EC2 service — only the image changes",
      ],
      example: { label: "Connect to each OS", lines: [
        "# Linux instance",
        "$ ssh -i my-key.pem ubuntu@13.234.x.x",
        "",
        "# Windows instance",
        "> mstsc /v:13.235.x.x        # Remote Desktop",
        "  (decrypt the Administrator password with your key first)",
      ] },
    },
    lifecycle: {
      ico: "🔄", title: "Instance Lifecycle Management", graphic: "ec2life",
      oneLine: "Starting, stopping, rebooting and terminating your servers to control cost and availability.",
      analogy: "💡 Like switching appliances on and off to save electricity — and unplugging ones you no longer need.",
      explain: "An EC2 instance moves through states: pending → running → stopping → stopped → terminated. While running you pay for compute. Stopping pauses compute billing (you keep the disk). Terminating deletes the instance permanently. Knowing these states is key to managing cost and reliability.",
      points: [
        "running = you're paying for compute",
        "stopped = compute billing paused (disk still kept)",
        "terminated = gone for good (deletes the instance)",
        "reboot = quick restart, keeps the same instance",
      ],
      example: { label: "Manage an instance's life", lines: [
        "$ aws ec2 stop-instances     --instance-ids i-0web01   # pause billing",
        "$ aws ec2 start-instances    --instance-ids i-0web01   # resume",
        "$ aws ec2 reboot-instances   --instance-ids i-0web01   # quick restart",
        "$ aws ec2 terminate-instances --instance-ids i-0web01  # delete forever",
      ] },
    },
    customvpc: {
      ico: "📐", title: "Custom VPC Design", graphic: "vpc", focus: "all",
      oneLine: "Designing your own complete network layout from scratch for a real application.",
      analogy: "📐 Like drawing the full floor plan of your house — rooms, doors, locks — before construction begins.",
      explain: "A typical production VPC spans two Availability Zones for resilience. Each AZ has a public subnet (web servers + load balancer) and a private subnet (app + database). An Internet Gateway serves the public subnets; a NAT Gateway lets private subnets reach out for updates without being reachable from outside. Route tables and security layers tie it together.",
      points: [
        "Span 2+ AZs for high availability",
        "Public subnets: load balancer + web tier",
        "Private subnets: app + database tier",
        "IGW for public; NAT for private outbound",
      ],
      example: { label: "A 2-tier, 2-AZ blueprint", lines: [
        "VPC 10.0.0.0/16",
        " ├─ AZ-a: subnet-pub-a (10.0.1.0/24)  subnet-priv-a (10.0.3.0/24)",
        " ├─ AZ-b: subnet-pub-b (10.0.2.0/24)  subnet-priv-b (10.0.4.0/24)",
        " ├─ IGW  -> public route tables (0.0.0.0/0)",
        " └─ NAT  -> private route tables (outbound updates only)",
      ] },
    },
    s3: {
      ico: "🪣", title: "Amazon S3 Fundamentals", graphic: "s3",
      oneLine: "Practically unlimited cloud storage for files, called objects, kept in buckets.",
      analogy: "☁️ Like an infinite Google Drive that can hold any file — photos, videos, backups, anything.",
      explain: "Simple Storage Service stores objects (files + metadata) inside buckets (globally-unique named containers). It offers eleven 9's of durability (99.999999999%), meaning your data is extraordinarily safe. You access objects via a URL or the API, and control access with policies. It's used for backups, media, data lakes and website assets.",
      points: [
        "Objects (files) live in buckets (containers)",
        "Bucket names are globally unique",
        "11 nines of durability — extremely safe",
        "Pay for storage used + requests + data transfer out",
      ],
      example: { label: "Create a bucket and upload a file", lines: [
        "$ aws s3 mb s3://my-app-assets-2026     # make bucket",
        "$ aws s3 cp logo.png s3://my-app-assets-2026/",
        "  upload: ./logo.png -> s3://my-app-assets-2026/logo.png ✅",
        "$ aws s3 ls s3://my-app-assets-2026",
        "  2026-06-29 11:20  24.1 KiB  logo.png",
      ] },
    },
    storageclasses: {
      ico: "🗂️", title: "S3 Storage Classes", graphic: "storage",
      oneLine: "Different S3 tiers that balance cost against how often and how fast you access data.",
      analogy: "🧥 Like keeping daily clothes in your closet, but winter coats in the attic — cheaper to store what you rarely touch.",
      explain: "Not all data is accessed equally. S3 Standard is for hot, frequently-used data. Standard-IA (Infrequent Access) is cheaper for data you rarely read. Glacier and Deep Archive are very cheap for long-term archives but take time to retrieve. Intelligent-Tiering automatically moves objects to the cheapest suitable tier.",
      points: [
        "Standard: frequent access, highest cost",
        "Standard-IA: rare access, cheaper storage",
        "Glacier / Deep Archive: cheap long-term archive",
        "Intelligent-Tiering: auto-optimises cost for you",
      ],
      example: { label: "Store an archive cheaply", lines: [
        "$ aws s3 cp backup-2025.zip s3://my-archive/ \\",
        "    --storage-class GLACIER",
        "  -> stored in Glacier (≈ 1/5 the cost of Standard)",
        "# Retrieval takes minutes-hours, but it's great for archives.",
      ] },
    },
    staticsite: {
      ico: "🌐", title: "Static Website Hosting", graphic: "staticsite",
      oneLine: "Serving a website's files (HTML/CSS/JS) directly from an S3 bucket — no server needed.",
      analogy: "📌 Like pinning your posters straight onto a public wall — no building, no staff, just the content.",
      explain: "For sites without server-side logic (like this very app!), S3 can host the files directly. You enable static website hosting on the bucket, set an index document, make the files public, and S3 serves them over HTTP. Pair it with CloudFront for HTTPS and global speed.",
      points: [
        "Great for HTML/CSS/JS sites & single-page apps",
        "Enable hosting + set index.html",
        "Add CloudFront for HTTPS + global caching",
        "Extremely cheap and scales automatically",
      ],
      example: { label: "Host a site from S3", lines: [
        "$ aws s3 website s3://my-site --index-document index.html",
        "$ aws s3 sync ./build s3://my-site --acl public-read",
        "  upload: index.html, styles.css, app.js ...",
        "  🌐 Live at http://my-site.s3-website.ap-south-1.amazonaws.com",
      ] },
    },
    rds: {
      ico: "🗄️", title: "Amazon RDS (MySQL)", graphic: "rds",
      oneLine: "A managed relational database that AWS runs, patches and backs up for you.",
      analogy: "🏠 Like a serviced apartment where the landlord handles all repairs — you just live (store data) in it.",
      explain: "Relational Database Service runs engines like MySQL, PostgreSQL and others, but handles the tedious operations: provisioning, patching, automated backups, and optional Multi-AZ failover. You get a database endpoint and connect your app to it — without managing the underlying server.",
      points: [
        "Managed MySQL/Postgres/etc. — no server admin",
        "Automated backups & point-in-time recovery",
        "Multi-AZ standby for automatic failover",
        "Read replicas to scale read-heavy workloads",
      ],
      example: { label: "Create a MySQL database", lines: [
        "$ aws rds create-db-instance \\",
        "    --db-instance-identifier shop-db \\",
        "    --engine mysql --db-instance-class db.t3.micro \\",
        "    --allocated-storage 20 --master-username admin ...",
        "  -> Endpoint: shop-db.xxxx.ap-south-1.rds.amazonaws.com:3306 ✅",
      ] },
    },
    dbconn: {
      ico: "🔌", title: "Database Connectivity", graphic: "rds", focus: "conn",
      oneLine: "How your application securely connects and talks to the database.",
      analogy: "☎️ Like a private phone line between your app and its filing cabinet — only the right caller gets through.",
      explain: "Your app connects using the RDS endpoint (host), a port (3306 for MySQL), a username and password, and the database name. Security is enforced by placing the DB in a private subnet and using a Security Group that only allows the app servers to reach it. Credentials are best stored in AWS Secrets Manager, not in code.",
      points: [
        "Connect with endpoint + port + user + password",
        "Keep the DB in a private subnet",
        "SG rule: only the app tier can reach the DB port",
        "Store secrets in Secrets Manager, never in code",
      ],
      example: { label: "App connection string", lines: [
        "DATABASE_URL = mysql://admin:****@shop-db.xxxx.rds.amazonaws.com:3306/shop",
        "",
        "# Security Group on the DB allows only the app servers:",
        "$ aws ec2 authorize-security-group-ingress --group-id sg-db \\",
        "    --protocol tcp --port 3306 --source-group sg-app",
      ] },
    },
    backup: {
      ico: "🛟", title: "Backup & Disaster Recovery", graphic: "rds", focus: "backup",
      oneLine: "Keeping safe copies so you can recover quickly after a failure or mistake.",
      analogy: "🔑 Like keeping a spare house key and an insurance policy — you hope you never need them, but you're glad they exist.",
      explain: "Things fail: disks die, regions have outages, people delete the wrong thing. Disaster recovery uses automated RDS snapshots, S3 versioning, Multi-AZ replication (a standby in another AZ), and sometimes cross-Region copies. You plan around two targets: RPO (how much data you can afford to lose) and RTO (how fast you must be back).",
      points: [
        "Automated snapshots + point-in-time restore",
        "Multi-AZ standby fails over automatically",
        "Copy backups to another Region for safety",
        "Plan for RPO (data loss) and RTO (recovery time)",
      ],
      example: { label: "Snapshot and restore", lines: [
        "$ aws rds create-db-snapshot --db-instance-identifier shop-db \\",
        "    --db-snapshot-identifier shop-db-2026-06-29",
        "# Disaster? Restore a brand-new DB from the snapshot:",
        "$ aws rds restore-db-instance-from-db-snapshot \\",
        "    --db-instance-identifier shop-db-restored \\",
        "    --db-snapshot-identifier shop-db-2026-06-29 ✅",
      ] },
    },
    peering: {
      ico: "🌉", title: "VPC Peering", graphic: "peering",
      oneLine: "A private one-to-one connection so two VPCs can talk using internal IPs.",
      analogy: "🌉 Like building a private bridge between two gated communities — residents pass directly without using public roads.",
      explain: "VPC Peering links two VPCs so resources communicate using private IPs, without going over the internet. It's not transitive — if A peers with B and B peers with C, A still can't reach C. For many networks, a Transit Gateway (next topic) is simpler.",
      points: [
        "Private connection between two VPCs",
        "Uses internal IPs — never touches the internet",
        "Not transitive (A↔B and B↔C ≠ A↔C)",
        "Update route tables on both sides",
      ],
      example: { label: "Peer two VPCs", lines: [
        "$ aws ec2 create-vpc-peering-connection \\",
        "    --vpc-id vpc-app --peer-vpc-id vpc-data",
        "$ aws ec2 accept-vpc-peering-connection --vpc-peering-connection-id pcx-01",
        "# Then add routes on BOTH VPCs pointing to each other's CIDR.",
      ] },
    },
    transit: {
      ico: "✈️", title: "Transit Gateway", graphic: "peering", focus: "hub",
      oneLine: "A central hub that connects many VPCs and on-prem networks at once.",
      analogy: "✈️ Like an airport hub linking many cities through one place — instead of a separate direct flight between every pair.",
      explain: "When you have many VPCs, peering each pair becomes a tangled mess. A Transit Gateway acts as a central router: every network connects once to the hub, and the hub routes traffic between them. It scales cleanly to hundreds of VPCs and VPN connections.",
      points: [
        "One central hub instead of many peerings",
        "Connect VPCs, VPNs and Direct Connect",
        "Scales to hundreds of networks",
        "Central place to manage routing",
      ],
      example: { label: "Attach VPCs to a hub", lines: [
        "$ aws ec2 create-transit-gateway              -> tgw-01",
        "$ aws ec2 create-transit-gateway-vpc-attachment \\",
        "    --transit-gateway-id tgw-01 --vpc-id vpc-app",
        "$ aws ec2 create-transit-gateway-vpc-attachment \\",
        "    --transit-gateway-id tgw-01 --vpc-id vpc-data",
        "# All attached VPCs can now route through the hub.",
      ] },
    },
    alb: {
      ico: "⚖️", title: "Application Load Balancer (ALB)", graphic: "alb",
      oneLine: "Spreads incoming web traffic evenly across many servers so none get overwhelmed.",
      analogy: "🤵 Like a restaurant host seating arriving guests evenly across all the tables, skipping any table that's closed.",
      explain: "An ALB sits in front of your servers and distributes HTTP/HTTPS requests across them. It checks each server's health and stops sending traffic to unhealthy ones. It can route by path or hostname (e.g. /api → one group, /shop → another), enabling smart, layer-7 routing.",
      points: [
        "Layer-7 (HTTP/HTTPS) load balancing",
        "Health checks skip unhealthy servers",
        "Path/host routing (/api vs /shop)",
        "Spans multiple AZs for resilience",
      ],
      example: { label: "How a request flows", lines: [
        "User -> https://shop.example.com",
        "        │",
        "        ▼   (ALB checks health, picks a healthy target)",
        "      [ALB] ──▶ web-1 ✅",
        "            ╲─▶ web-2 ✅",
        "            ╲─▶ web-3 ✖ (unhealthy — skipped)",
      ] },
    },
    targets: {
      ico: "🎯", title: "Target Groups", graphic: "alb", focus: "targets",
      oneLine: "The set of servers a load balancer is allowed to send traffic to, plus their health rules.",
      analogy: "📋 Like the host's list of which tables are open — only those on the list get seated guests.",
      explain: "A Target Group is a named collection of targets (EC2 instances, IPs, or Lambda functions) registered behind a load balancer. It defines the health check (path, interval, thresholds) that decides if each target is healthy. ALB listener rules forward matching requests to a target group.",
      points: [
        "Holds the registered targets (EC2/IP/Lambda)",
        "Defines the health check used by the ALB",
        "Listener rules forward traffic to a group",
        "One ALB can route to several target groups",
      ],
      example: { label: "Create and register a target group", lines: [
        "$ aws elbv2 create-target-group --name web-tg \\",
        "    --protocol HTTP --port 80 --vpc-id vpc-0a1b2c \\",
        "    --health-check-path /healthz",
        "$ aws elbv2 register-targets --target-group-arn <tg> \\",
        "    --targets Id=i-0web01 Id=i-0web02",
      ] },
    },
    asg: {
      ico: "📈", title: "Auto Scaling Groups (ASG)", graphic: "asg",
      oneLine: "Automatically adds or removes servers based on real-time demand.",
      analogy: "🧑‍🤝‍🧑 Like calling in extra cashiers when the queue grows, then sending them home when it's quiet — automatically.",
      explain: "An Auto Scaling Group keeps a desired number of identical instances running and changes that number based on rules (e.g. 'add an instance when average CPU > 70%'). It also replaces any instance that fails a health check, and works with the ALB so new servers automatically receive traffic. Result: you handle traffic spikes without overpaying when it's quiet.",
      points: [
        "Maintains min / desired / max instance counts",
        "Scales out on high load, scales in when calm",
        "Auto-replaces unhealthy instances (self-healing)",
        "Integrates with ALB so new servers get traffic",
      ],
      example: { label: "A CPU-based scaling policy", lines: [
        "$ aws autoscaling create-auto-scaling-group --auto-scaling-group-name web-asg \\",
        "    --min-size 2 --max-size 10 --desired-capacity 2 ...",
        "$ aws autoscaling put-scaling-policy --auto-scaling-group-name web-asg \\",
        "    --policy-name cpu70 --target-tracking-configuration \\",
        "    '{\"TargetValue\":70,\"PredefinedMetricSpecification\":{\"PredefinedMetricType\":\"ASGAverageCPUUtilization\"}}'",
        "# Busy? It grows toward 10. Quiet? It shrinks back to 2.",
      ] },
    },
    lambda: {
      ico: "⚡", title: "AWS Lambda Fundamentals", graphic: "lambda",
      oneLine: "Run your code without provisioning or managing any servers at all.",
      analogy: "🥤 Like a vending machine: drop in a request, it runs and gives you a result, then powers down. No kitchen to maintain.",
      explain: "Lambda is 'serverless' compute. You upload a function; AWS runs it only when an event triggers it (an HTTP call, a file landing in S3, a queue message…). It scales automatically from zero to thousands of parallel runs, and you pay only for the milliseconds it executes — nothing when idle.",
      points: [
        "No servers to manage — just your function code",
        "Triggered by events (API, S3, queues, schedules)",
        "Scales automatically; pay only per execution",
        "Great for APIs, automation and glue code",
      ],
      example: { label: "A tiny Lambda function", lines: [
        "exports.handler = async (event) => {",
        "  const name = event.name || 'world';",
        "  return { statusCode: 200, body: `Hello, ${name}!` };",
        "};",
        "",
        "# Triggered by an API call -> runs in ~ms -> returns -> sleeps.",
        "# You pay only for those milliseconds.",
      ] },
    },
    dynamo: {
      ico: "🗃️", title: "Amazon DynamoDB", graphic: "dynamo",
      oneLine: "A super-fast, fully-managed NoSQL database that scales effortlessly.",
      analogy: "🔐 Like a giant wall of instant lockers: give the key (the item's id), get the contents in milliseconds.",
      explain: "DynamoDB is a key-value and document database delivering single-digit millisecond responses at any scale. There are no servers to manage and no fixed schema — each item is found by its primary key. It's ideal for high-traffic apps: shopping carts, gaming, IoT, user sessions.",
      points: [
        "NoSQL key-value / document store",
        "Single-digit millisecond latency at huge scale",
        "Fully managed & serverless — no capacity to babysit",
        "Flexible schema; items found by primary key",
      ],
      example: { label: "Put and get an item", lines: [
        "$ aws dynamodb put-item --table-name Users \\",
        "    --item '{\"userId\":{\"S\":\"u123\"},\"name\":{\"S\":\"Asha\"}}'",
        "$ aws dynamodb get-item --table-name Users \\",
        "    --key '{\"userId\":{\"S\":\"u123\"}}'",
        "  -> { name: \"Asha\" }   (returned in a few milliseconds ⚡)",
      ] },
    },
  };

  // Flat ordered list of ids for prev/next navigation
  const order = sessions.reduce((a, s) => a.concat(s.ids), []);

  window.DATA.aws = { sessions, lessons: L, order };
})();
